### ISSUE TITLE
crpy config redis:latest fails

### ISSUE THREAD

**Issue by bvanelli** [bvanelli/crpy#3]
```
python crpy/cmd.py config redis:latest                                                                              git:feature/image-utilities*
Authenticated at index.docker.io/library/redis:latest
Traceback (most recent call last):
  File "/Users/brunno.vanelli/Documents/git/crpy/crpy/cmd.py", line 277, in <module>
    main()
  File "/Users/brunno.vanelli/Documents/git/crpy/crpy/cmd.py", line 270, in main
    asyncio.run(arguments.func(arguments))
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/brunno.vanelli/Documents/git/crpy/crpy/cmd.py", line 71, in _inspect_config
    raw_config = await ri.get_config()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/async_lru/__init__.py", line 294, in __call__
    return await self.__wrapper(self.__instance, *fn_args, **fn_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/async_lru/__init__.py", line 227, in __call__
    return await asyncio.shield(fut)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brunno.vanelli/Documents/git/crpy/crpy/registry.py", line 274, in get_config
    config_digest = manifest["config"]["digest"]
                    ~~~~~~~~^^^^^^^^^^
KeyError: 'config'

```

**Comment by bvanelli** [comment]
Closed in #2
